name: Keystore Generation

on:
  push:
    paths:
      - 'dev/**'
      - 'stg/**'
      - 'prod/**'
  pull_request:
    paths:
      - 'dev/**'
      - 'stg/**'
      - 'prod/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cabextract default-jre-headless
      - name: Generate Initial Keystore
        run: |
          # Create directories
          mkdir -p trustedTpm/unzip

          # Download TrustedTpm.cab
          echo "Downloading TrustedTpm.cab..."
          curl -L --output trustedTpm/TrustedTpm.cab "https://go.microsoft.com/fwlink/?linkid=2097925"

          # Test and extract TrustedTpm.cab
          echo "Testing the integrity of the CAB file..."
          cabextract -q --test trustedTpm/TrustedTpm.cab
          
          echo "Extracting TrustedTpm.cab..."
          cabextract -q trustedTpm/TrustedTpm.cab --directory trustedTpm/unzip/

          # Initialize or update the keystore with certificates from extracted files
          KEYSTORE="trusted-tpm.jks"
          STOREPASS="changeit"

          echo "Importing certificates from TrustedTpm into the keystore..."
          # for file in trustedTpm/unzip/*/*/*.{cer,CER,crt,der}; do
          #     if [[ -f "$file" ]]; then
          #         ALIAS=$(basename "$file")
                  
          #         # Check if alias already exists in keystore
          #         if keytool -list -keystore "$KEYSTORE" -storepass "$STOREPASS" -alias "$file" >/dev/null 2>&1; then
          #             echo "Alias $ALIAS already exists, skipping import for $file."
          #         else
          #             echo "Importing $file as alias $ALIAS..."
          #             keytool -import -file "$file" -alias "$file" -keystore "$KEYSTORE" -storepass "$STOREPASS" -storetype jks -noprompt
          #         fi
          #     fi
          # done

          # Import certificates from dev, stg, and prod folders
          for ENV in dev stg prod; do
              echo "Importing certificates from $ENV environment..."
              for file in $ENV/*.{cer,CER,crt,der}; do
                  if [[ -f "$file" ]]; then
                      ALIAS="${ENV}-$(basename "$file")"
                      
                      # Check if alias already exists in keystore
                      if keytool -list -keystore "$KEYSTORE" -storepass "$STOREPASS" -alias "$file" >/dev/null 2>&1; then
                          echo "Alias $ALIAS already exists, skipping import for $file."
                      else
                          echo "Importing $file as alias $ALIAS..."
                          keytool -import -file "$file" -alias "$file" -keystore "$KEYSTORE" -storepass "$STOREPASS" -storetype jks -noprompt
                      fi
                  fi
              done
          done

          # Count certificates in the keystore
          echo "Counting certificates in the keystore..."
          CERT_COUNT=$(keytool -list -keystore "$KEYSTORE" -storepass "$STOREPASS" | grep 'trustedCertEntry' | wc -l)

          echo "Number of certificates in the keystore: $CERT_COUNT"
          
      - name: Upload Keystore as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: trusted-tpm.jks
          path: trusted-tpm.jks
