name: Keystore Generation

on:
  push:
    paths:
      - 'dev/**'
      - 'stg/**'
      - 'prod/**'
  pull_request:
    paths:
      - 'dev/**'
      - 'stg/**'
      - 'prod/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cabextract default-jre-headless

      - name: Generate Initial Keystore
        run: |
          # Create directories
          mkdir -p trustedTpm/unzip

          # Download TrustedTpm.cab
          echo "Downloading TrustedTpm.cab..."
          curl -L --output trustedTpm/TrustedTpm.cab "https://go.microsoft.com/fwlink/?linkid=2097925"

          # Test and extract TrustedTpm.cab
          echo "Testing the integrity of the CAB file..."
          cabextract -q --test trustedTpm/TrustedTpm.cab
          
          echo "Extracting TrustedTpm.cab..."
          cabextract -q trustedTpm/TrustedTpm.cab --directory trustedTpm/unzip/

          # Initialize or update the keystore with certificates from extracted files
          KEYSTORE="trusted-tpm.jks"
          STOREPASS="changeit"

          echo "Importing certificates into the keystore..."
          for file in trustedTpm/unzip/*/*/*.{cer,CER,crt,der}; do
              if [[ -f "$file" ]]; then
                  ALIAS=$(basename "$file")
                  echo "Importing $file as alias $ALIAS..."
                  keytool -import -file "$file" -alias "$ALIAS" -keystore "$KEYSTORE" -storepass "$STOREPASS" -storetype jks -noprompt
              fi
          done

          # Count certificates in the keystore
          echo "Counting certificates in the keystore..."
          CERT_COUNT=$(keytool -list -keystore "$KEYSTORE" -storepass "$STOREPASS" | grep 'trustedCertEntry' | wc -l)

          echo "Number of certificates in the keystore: $CERT_COUNT"
